//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatRoom
    {
        public ChatRoom()
        {
            this.Messages = new HashSet<Message>();
        }
    
        public int ChatID { get; set; }
        public string Owner { get; set; }
        public string ChatRoomName { get; set; }
    
        public virtual ICollection<Message> Messages { get; set; }
    }
}
